config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
#     root :to => 'users#index'
      root :to => 'patients#search'
      get '/admin' => 'users#index'

      get '/sign_out' => 'users/sessions#destroy'
      #get 'userstatus' => 'users#changestatus'
      get 'userstatus/:id' => 'users#changestatus', :as => :userstatus
      get 'changepassword/:id' => 'users#changepassword', :as => :changepassword
      patch 'updatepassword/:id' => 'users#updatepassword'
#     match "/userstatus/:id" => 'users#changestatus'
      get 'home' => 'patients#index'
      get 'search' => 'patients#search'
      get 'what' => 'patients#what'
#     get 'createrecord' => 'patients#create'
      post 'saverecord' => 'patients#multisave'
      get 'allrecords' => 'patients#index'
      get 'bulkcreate' => 'patients#bulkcreate'
      get 'export' => 'patients#export'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :patients
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
       

 

  #validates :password_confirmation, presence: true
  
  #validates :name, presence: true 
  #validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  #validates :status, presence: true
  #validates :isadmin, presence: true
  
  def self.navigators_for_select
    where(status: true).map {|user| [user.name, user.id] }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :changepassword, :updatepassword]

  def index
    # @users = User.all
    @users=User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
  
  def changestatus
    @users = User.find(params[:id])
    Rails.logger.info(@users[:status])
    if @users[:status]==false
      status = true;
      message = 'User ( '+@users.email+' ) account activated'
    else
      status = false;
      message = 'User ( '+@users.email+' ) account deactivated'
    end
    if User.where(:id => params[:id]).update_all(:status => status)
      redirect_to users_path, :notice => message
    else
      redirect_to users_path, :alert => 'Unable to process, please try again after sometime'
    end
  end
  
  def edit
  end
  
  def changepassword
  end
  
  def updatepassword
    respond_to do |format|
      Rails.logger.info(changepassword)
      if @user.update(changepassword)
        format.html { redirect_to users_path(@user), notice: 'Password was successfully updated.' }
      else
        format.html { render action: 'changepassword' }
      end
    end
  end
  
  def update
    respond_to do |format|
      Rails.logger.info(user_params)
      if @user.update(user_params)
        format.html { redirect_to users_path(@user), notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :status, :isadmin)
    end
    
     def changepassword
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/users/_form.html.erb
<div class="header_login">
<div class="container">
<div class="header_login_box">
 
<%= form_for(@user) do |f| %>
  <%= render partial: "shared/error_messages", locals: { model: @user } %>
    <ul>
        <li>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </li>
        <li>
          <%= f.label :email %>           
          <%= f.text_field :email %>
        </li>
        <li>
          <%= link_to "Back", users_path, class: "btn btn-default left" %>
          <%= f.submit "Save", class: "btn btn-primary white right"%>
        </li>
      </ul>
      <% end %>
    </div>
    
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/changepassword.erb
<div class="header_login">
<div class="container">
<div class="header_login_box">
 
<%= form_for(@user, :url => { :action => :updatepassword, :controller =>:users }) do |f| %>
    <%= render partial: "shared/error_messages", locals: { model: @user } %>
   
    <ul>
      <li>
        <%= f.label :password %>
        <%= f.password_field :password, :autocomplete => 'off' %>
      </li>
      <li>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </li>  
      <li>
        <%= link_to "Back", users_path, class: "btn btn-default left" %>
        <%= f.submit "Save", class: "btn btn-primary white right"%>
      </li>
      </ul>
      <% end %>
    </div>
    
  </div>
</div>

app/views/users/edit.html.erb
<h2>Update Profile</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h2>Registered users</h2>
<div class="table-responsive">
  <table class="records table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>E-mail</th>
        <th>Admin</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.isadmin %></td>
          <td>
          <% if current_user == user || current_user.isadmin %>
            <%= link_to 'Edit Details', edit_user_path(user), class: "btn btn-primary btn-xs white" %>
          <% end %>
          </td>
          <td>
          <% if current_user == user || current_user.isadmin %>
            <%= link_to 'Change Password', changepassword_path(user), class: "btn btn-primary btn-xs white" if current_user.isadmin || current_user == user %>
          <% end %>
          </td>
          <td>
            <% if current_user.isadmin %>
              <%
                if user.status == false
                  link_to 'Activate', userstatus_path(user), method: :get, class: "btn btn-danger btn-xs white"
                else
                  link_to 'Deactivate', userstatus_path(user), method: :get,class: "btn btn-danger btn-xs white"
                end
              %>
            <% end %>
        </td>
        </tr>
      <% end %>
        <tr>
            <td colspan="7">
                <%= paginate @users %>
            </td>
        </tr>
    </tbody>
  </table>
</div>
<br>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>