config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
#     root :to => 'users#index'
      root :to => 'patients#search'
      get '/admin' => 'users#index'

      get '/sign_out' => 'users/sessions#destroy'
      #get 'userstatus' => 'users#changestatus'
      get 'userstatus/:id' => 'users#changestatus', :as => :userstatus
      get 'changepassword/:id' => 'users#changepassword', :as => :changepassword
      patch 'updatepassword/:id' => 'users#updatepassword'
#     match "/userstatus/:id" => 'users#changestatus'
      get 'home' => 'patients#index'
      get 'search' => 'patients#search'
      get 'what' => 'patients#what'
#     get 'createrecord' => 'patients#create'
      post 'saverecord' => 'patients#multisave'
      get 'allrecords' => 'patients#index'
      get 'bulkcreate' => 'patients#bulkcreate'
      get 'export' => 'patients#export'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :patients
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!--<footer>
  © Company 2014
</footer>-->

app/views/shared/_header.erb
<div class="header">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-4">
		<%= image_tag "logo.png" %>
            </div>
            <div class="login_right">
		<% if @current_user.admin? %>
		   <%= link_to "Users", users_path %>
                <%= link_to "Search", search_path %>
                <% end %>
                   <%= link_to "Saved Records", allrecords_path %>
		   <%= link_to "Profile", edit_user_path(@current_user) %>
                   <%= link_to "Logout", logout_path, method: :delete %>
            </div>
        </div>
    </div>

</div>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'NewApp', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if @current_user.admin? %>
          <li><%= link_to 'Users', users_path %></li>
        <% end %>
        <li><%= link_to 'Link2' %></li>
        <li class="dropdown">
          <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            Dropdown <b class="caret"></b
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Link3' %></li>
            <li><%= link_to 'Link4' %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav" style="float:right">
        <li class="dropdown">
          <%= link_to '#', class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <span class='glyphicon glyphicon-user'></span> <%= @current_user.username %> <b class='caret'></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Settings", edit_user_path(@current_user) %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>