config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
#     root :to => 'users#index'
      root :to => 'patients#search'
      get '/admin' => 'users#index'

      get '/sign_out' => 'users/sessions#destroy'
      #get 'userstatus' => 'users#changestatus'
      get 'userstatus/:id' => 'users#changestatus', :as => :userstatus
      get 'changepassword/:id' => 'users#changepassword', :as => :changepassword
      patch 'updatepassword/:id' => 'users#updatepassword'
#     match "/userstatus/:id" => 'users#changestatus'
      get 'home' => 'patients#index'
      get 'search' => 'patients#search'
      get 'what' => 'patients#what'
#     get 'createrecord' => 'patients#create'
      post 'saverecord' => 'patients#multisave'
      get 'allrecords' => 'patients#index'
      get 'bulkcreate' => 'patients#bulkcreate'
      get 'export' => 'patients#export'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users
  resources :patients
end

app/models/patient.rb
class Patient < ActiveRecord::Base

  validates :startdate, presence: true
  validates :starttime, presence: true
  # validates :initialcontact, presence: true
  validates :agerange, presence: true
  validates :gender, presence: true
  validates :languagespeaking, presence: true
  validates :languagereading, presence: true
  validates :computer, presence: true
  validates :computerskills, presence: true
  validates :topicdiscussed, presence: true
  validates :timelength, presence: true
  validates :notes, presence: true
  validates :noofparticipant, presence: true
  validates :noofinteraction, presence: true
  validates :location, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |patient|
        csv << patient.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:update]
  
  def index
    if current_user[:isadmin]
      @patients = Patient.all.order(id: :desc).page(params[:page]).per(10)
    else
      @patients=Patient.where(userid: session[:user_id]).order(id: :desc).page(params[:page]).per(10)
    end
  end
  
  def search
    gender = params[:gender]
    location = params[:location]   
    topic = params[:topic]
    duration = params[:duration]
    type = params[:type]
    computer = params[:computer]

    if (params.has_key?(:fromdate) &&   !params[:fromdate].blank?)
      fromdate = Date.strptime(params[:fromdate], "%m/%d/%Y").to_s(:db)
    else
      fromdate = Date.strptime('01/01/1970', "%m/%d/%Y").to_s(:db)
    end
    
    if (params.has_key?(:todate) && !params[:todate].blank?)
      todate = Date.strptime(params[:todate], "%m/%d/%Y").to_s(:db)
    else
      todate = Date.strptime('12/31/2100', "%m/%d/%Y").to_s(:db)
    end
      @patients = Patient.where("gender LIKE ? AND  location LIKE ? AND topicdiscussed LIKE ? AND timelength LIKE ? AND noofparticipant LIKE ? AND computer LIKE ? AND startdate >= ? AND startdate <= ?","%#{gender}%","%#{location}%","%#{topic}%","%#{duration}%","%#{type}%","%#{computer}%","%#{fromdate}%","%#{todate}%").order(id: :desc).page(params[:page]).per(10)
   end
  
  def export
    @patients = Patient.all.order(id: :desc)
    respond_to do |format|
      format.html
      format.csv { send_data @patients.to_csv }
      format.xls { send_data @patients.to_csv(col_sep: "\t") }
    end
  end

   # GET /patients/new
  def new
    @patient = Patient.new
  end
  
  def bulkcreate
    if current_user[:isadmin]
      @patients = Patient.all.last(10).reverse
    else
      @patients=Patient.where(userid: session[:user_id]).last(10).reverse
    end
    @patient = Patient.new
  end

  def multisave
    if params1[:startdate1]!=''
      startdate1 = Date.strptime(params1[:startdate1], "%m/%d/%Y")
    end
    if params2[:startdate2]!=''
      startdate2 = Date.strptime(params2[:startdate2], "%m/%d/%Y")
    end
    if params3[:startdate3]!=''
      startdate3 = Date.strptime(params3[:startdate3], "%m/%d/%Y")
    end
    
    @patient1 = Patient.create(userid: params1[:userid], startdate: startdate1, starttime: params1[:starttime1], initialcontact: params1[:initialcontact1], agerange: params1[:agerange1], gender: params1[:gender1], languagespeaking: params1[:languagespeaking1], languagereading: params1[:languagereading1], computer: params1[:computer1], computerskills: params1[:computerskills1], topicdiscussed: params1[:topicdiscussed1], timelength: params1[:timelength1], notes: params1[:notes1], noofparticipant: params1[:noofparticipant1], noofinteraction: params1[:noofinteraction1], location: params1[:location1])
    respond_to do |format|
      if @patient1.save
        if params2[:location2]
          @patient2 = Patient.create(userid: params2[:userid], startdate: startdate2, starttime: params2[:starttime2], initialcontact: params2[:initialcontact2], agerange: params2[:agerange2], gender: params2[:gender2], languagespeaking: params2[:languagespeaking2], languagereading: params2[:languagereading2], computer: params2[:computer2], computerskills: params2[:computerskills2], topicdiscussed: params2[:topicdiscussed2],  timelength: params2[:timelength2], notes: params2[:notes2], noofparticipant: params2[:noofparticipant2], noofinteraction: params2[:noofinteraction2], location: params2[:location2])
          @patient2.save
        end
        if params3[:location3]
          @patient3 = Patient.create(userid: params3[:userid], startdate: startdate3, starttime: params3[:starttime3], initialcontact: params3[:initialcontact3], agerange: params3[:agerange3], gender: params3[:gender3], languagespeaking: params3[:languagespeaking3], languagereading: params3[:languagereading3], computer: params3[:computer3], computerskills: params3[:computerskills3], topicdiscussed: params3[:topicdiscussed3],  timelength: params3[:timelength3], notes: params3[:notes3], noofparticipant: params3[:noofparticipant3], noofinteraction: params3[:noofinteraction3], location: params3[:location3])
          @patient3.save
        end
        format.html { redirect_to bulkcreate_path, notice: 'Data successfully saved' }
      else
        format.html { render action: 'create' }
      end
    end
  end
  
   # POST /create
  def create
    if create_params[:startdate]!=''
      startdate = Date.strptime(create_params[:startdate], "%m/%d/%Y")
    end
      @patient = Patient.create(userid: create_params[:userid], startdate: startdate, starttime: create_params[:starttime], initialcontact: create_params[:initialcontact], agerange: create_params[:agerange], gender: create_params[:gender], languagespeaking: create_params[:languagespeaking], languagereading: create_params[:languagereading], computer: create_params[:computer], computerskills: create_params[:computerskills], topicdiscussed: create_params[:topicdiscussed],  timelength: create_params[:timelength], notes: create_params[:notes], noofparticipant: create_params[:noofparticipant], noofinteraction: create_params[:noofinteraction], location: create_params[:location])

      respond_to do |format|
        if @patient.save
          format.html { redirect_to patients_path, notice: 'Data successfully saved' }
        else
          format.html { render action: 'create' }
        end
      end
  end

  # GET /patients/1/show
  def show
    @patient = Patient.find(params[:id])
  end
  
   # GET /users/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end
  
   # PATCH/PUT /patients/1
  def update
      if params[:patient][:startdate]!=''
        startdate = Date.strptime(params[:patient][:startdate], "%m/%d/%Y")
      end 

    #Rails.logger.info(startdate)

    respond_to do |format|
      if @patient.update(edit_params)
        Patient.where(:id => params[:id]).update_all(:startdate => startdate)
        format.html { redirect_to edit_patient_path(@patient), notice: 'Record was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end
  
   # DELETE /parients/1
  def destroy
    respond_to do |format|
      @patient = Patient.find(params[:id])
      if @patient.destroy
        format.html { redirect_to :back, notice: 'Record was successfully deleted.' }
      else
        format.html { redirect_to :back, alert: 'Record could not be deleted.'}
      end
    end
  end

  private
  
    def set_patient
      @patient = Patient.find(params[:id])
    end
    
    def create_params
      params.require(:patient).permit(:startdate, :starttime, :initialcontact, :agerange, :gender, :languagespeaking, :languagereading, :computer, :computerskills, :topicdiscussed, 
:topicdiscussed, :timelength, :notes, :noofparticipant, :noofinteraction, :userid, :location)
    end
    
    def edit_params
      params.require(:patient).permit(:starttime, :initialcontact, :agerange, :gender, :languagespeaking, :languagereading, :computer, :computerskills, :topicdiscussed, 
:topicdiscussed, :timelength, :notes, :noofparticipant, :noofinteraction, :userid, :location)
    end
    
    def params1
      params.require(:patient).permit(:startdate1, :starttime1, :initialcontact1, :agerange1, :gender1, :languagespeaking1, :languagereading1, :computer1, :computerskills1, :topicdiscussed1, 
:topicdiscussed1, :timelength1, :notes1, :noofparticipant1, :noofinteraction1, :userid, :location1)
    end
    
    def params2
      params.require(:patient).permit(:startdate2, :starttime2, :initialcontact2, :agerange2, :gender2, :languagespeaking2, :languagereading2, :computer2, :computerskills2, :topicdiscussed2, 
:topicdiscussed2, :timelength2, :notes2, :noofparticipant2, :noofinteraction2, :userid, :location2)
    end
    
    def params3
      params.require(:patient).permit(:startdate3, :starttime3, :initialcontact3, :agerange3, :gender3, :languagespeaking3, :languagereading3, :computer3, :computerskills3, :topicdiscussed3, 
:topicdiscussed3, :timelength3, :notes3, :noofparticipant3, :noofinteraction3, :userid, :location3)
    end
end

app/views/patients/_form.html.erb
<div class="header_login">
<div class="container">
<div class="login_after">

<%= form_for(@patient) do |f| %>
     <%= render partial: "shared/error_messages", locals: { model: @patient  } %>
    <script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker();
        jQuery('#timepicker').timepicker();
      });
    </script>
     <ul>
            <input name="patient[userid]" type="hidden" value="<%= current_user[:id] %>"/>
            <li>
              <%= f.label :navigator, 'Navigator' %>
              <%= f.select(:navigator_id, options_for_select(User.navigators_for_select, @patient.navigator_id )) %>
            </li>

            <li>
                <%= f.label :initial_contact %>
                <%
              if (@patient.startdate.present?)
                form_date = formatted_date(@patient.startdate) 
              else
                form_date=''
              end
              %>
                <%= text_field_tag 'patient[startdate]', form_date , "data-provide"=>"datepicker", placeholder: 'mm/dd/yyyy' %>
            </li>
            <li>
              <%= f.label :start_time %>
              <%= f.text_field :starttime, id: "timepicker" %>
            </li>

            <li>
              <%= f.label :location %>
              <%= f.select(:location, options_for_select(["Prieto", "Sengstacke", "A.C.T.S. OF F.A.I.T.H.", "Ann & Robert H. Lurie Children’s Hospital","Cook County Health and Hospitals System (CCHHS)", "Erie Family Health Center", "Family Focus", "Health Leads – Chicago", "Heartland Health Outreach", "Komed Holman Health Center"], @patient.location )) %>
            </li>
             <li>
              <%= f.label :length_of_time_with_patient, 'Length of Time With Client' %>
              <%= f.select(:timelength, options_for_select(['10 MIN', '20 MIN', '30 MIN', '40 MIN', '1 HR'], @patient.timelength )) %>
            </li>

            <li>
              <%= f.label :type_of_interaction, 'Type of Interaction' %>
              <%= f.select(:noofinteraction, options_for_select(['Individual', 'Group'], @patient.noofinteraction )) %>
            </li>

            <li>
                <%= f.label :group_id, 'Group ID' %>
                <%= f.text_field :groupid %>
            </li>
            <li>
              <%= f.label :no_of_visits, 'Number of Client Interactions' %>
              <%= f.select(:noofvisits, options_for_select(['Initial', '1-2', '3-5', '6-10','10+'], @patient.noofvisits )) %>
            </li>
            <li>
              <%= f.label :gender %>
              <%= f.select(:gender, options_for_select(['Male', 'Female','Other'], @patient.gender )) %>
            </li>
            <li>
                <%= f.label :age %>
                <%= f.select(:agerange, options_for_select(['10-15', '15-20', '20-25', '25-30', '30-35', '35-40', '40-45', '45-50', '50-60', '60-80', '80-100'], @patient.agerange )) %>
            </li>
            <li>
              <%= f.label :preferred_language %>
              <%= f.select(:languagespeaking, options_for_select(['English','Spanish','Polish', 'Vietnamese', 'French/Creole']  , @patient.languagespeaking )) %>
            </li>
            <li>
              <%= f.label :language_reading, 'Language Reading' %>
              <%= f.select(:languagereading, options_for_select(['English','Spanish','Polish', 'Vietnamese', 'French/Creole']  , @patient.languagereading )) %>
            </li>
            <li>
              <%= f.label :own_computer? %>
              <%= f.select(:computer, options_for_select(['Yes', 'No'], @patient.computer )) %>
            </li>
            <li>
              <%= f.label :Computer_Skills %>
              <%= f.select(:computerskills, options_for_select(['None', 'Beginner', 'Intermediate', 'Advanced'], @patient.computerskills )) %>
            </li>
            <li>
              <%= f.label :Navigator_notes_OR_observations %>
              <%= f.text_field :notes %>
            </li>
            <li>
              <%= f.label :topics_discussed %>
              <%= f.select(:topicdiscussed, options_for_select(['Diabetes', 'Heart Disease', 'HIV', 'Asthma', 'Stroke', 'Excercise', 'Hypertension and Nutrition'], @patient.topicdiscussed )) %>
            </li>
            <li>
              <%= link_to "Back", :back, class: "btn btn-default left" %>
              <%= f.submit "Save", class: "btn btn-primary white right" %>
            </li>
        </ul>
      <% end %>
    </div>
    
   

  </div>
</div>

app/views/patients/create.html.erb
<h2>Create Record</h2>
<%= render 'form' %>

app/views/patients/edit.html.erb
<h2>Update Record</h2>
<%= render 'form' %>

app/views/patients/export.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Gender</Data></Cell>
    
      </Row>
    <% @patients.each do |patient| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= patient.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= patient.gender %></Data></Cell>
       
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/patients/index.html.erb
<h2>Records</h2>
<div class="table-responsive">
  <table class="records table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Initial Contact</th>
        <th>Age Range</th>
        <th>Gender</th>
	<th>Time Length</th>
	<th>Participants (nos)</th>
	<th>Interaction</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td colspan='18' style='align:left'>
            <%= link_to "CSV", export_path(format: "csv"), class: "btn btn-primary btn-xs white" %> |
            <%= link_to "Excel", export_path(format: "xls"), class: "btn btn-primary btn-xs white" %>
          </td>
        </tr>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.id %></td>
          <td><%= formatted_date(patient.startdate) %></td>
          <td><%= patient.agerange %></td>
          <td><%= patient.gender %></td>
	  <td><%= patient.timelength %></td>
	  <td><%= patient.noofparticipant %></td>
	  <td><%= patient.noofinteraction %></td>
          <td><%= link_to 'Details', patient_path(patient), class: "btn btn-primary btn-xs white" %></td>
          <td><%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-primary btn-xs white" %></td>
          <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs white" %></td>	
        </tr>
      <% end %>
         <tr>
            <td colspan="10">
                <%= paginate @patients %>
            </td>
        </tr>
    </tbody>
  </table>
</div>
<br>
<%=  link_to 'Create Record', new_patient_path, class: "btn btn-primary white" %>
<%= link_to 'Bulk Create', bulkcreate_path, class: "btn btn-primary white" %>	

app/views/patients/new.html.erb
<h2>Create Record</h2>
<%= render 'form' %>

app/views/patients/search.erb
<script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker();
      });
</script>
<h2>Search</h2>
<div class="table-responsive">
    
  <table class="records table">
       <thead>
      
        <tr>
          <td colspan='7'>
              <%= form_tag search_path, :method => 'get', :id => "patient_search" do %>
            <table>
              <tr>
                <td>
                  Select date Range
                </td>
                <td>
                  From date
                </td>
                <td>

                  <%= text_field_tag 'fromdate', params[:fromdate] , "data-provide"=>"datepicker" %>
                </td>
                <td>
                  To date
                </td>
                <td>
                  <%= text_field_tag 'todate', params[:todate] , "data-provide"=>"datepicker" %>
                </td>
              </tr>
           
        <tr>
          <td>
              Gender
              <%= select_tag "gender", options_for_select(['Male', 'Female', 'Other'], params[:gender]), :include_blank => 'ALL' %>
          </td>
          <td>
              Location
              <%= select_tag "location", options_for_select(["Prieto", "Sengstacke", "A.C.T.S. OF F.A.I.T.H.", "Ann & Robert H. Lurie Children’s Hospital","Cook County Health and Hospitals System (CCHHS)", "Erie Family Health Center", "Family Focus", "Health Leads – Chicago", "Heartland Health Outreach", "Komed Holman Health Center"], params[:location]), :include_blank => 'ALL' %>
          </td>
          <td>
              Topic
              <%= select_tag "topic", options_for_select(['Diabetes', 'Heart Disease', 'HIV', 'Asthma', 'Stroke', 'Excercise', 'Hypertension and Nutrition'], params[:topic]), :include_blank => 'ALL' %>
          </td>
          <td>
              Duration
              <%= select_tag "duration", options_for_select(['10 MIN', '20 MIN', '30 MIN', '40 MIN', '1 HR'], params[:duration]), :include_blank => 'ALL' %>
          </td>
          <td>
              Computer
              <%= select_tag "computer", options_for_select(['Yes', 'No'], params[:computer]), :include_blank => 'ALL' %>
          </td>
          <td>
              Type </br>
              <%= select_tag "type", options_for_select(['Group', 'Individual'], params[:type]), :include_blank => 'ALL' %>
          </td>
          <td>
              <%= submit_tag "Search", :name => 'search' %></p>
          </td>
        </tr>
        </table>
      <% end %>
          </td>
        </tr>
      <tr>
        <th>ID</th>
        <th>Initial Contact</th>
        <th>Age Range</th>
        <th>Gender</th>
	<th>Time Length</th>
	<th>Participants (nos)</th>
	<th>Interaction</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.id %></td>
          <td><%= patient.initialcontact %></td>
          <td><%= patient.agerange %></td>
          <td><%= patient.gender %></td>
	  <td><%= patient.timelength %></td>
	  <td><%= patient.noofparticipant %></td>
	  <td><%= patient.noofinteraction %></td>
              </tr>
      <% end %>
         <tr>
            <td colspan="10">
                <%= paginate @patients %>
            </td>
        </tr>
    </tbody>
  </table>
</div>	

app/views/patients/search.html.erb
 <script type="text/javascript">
// $(document).ready(function(){
//  $('.get_patient_id').on('click', function(){
//     alert('hello');
//     var customerId = [];
//     var count_id = 0;
//     $('[id="patient_id"]').each(function() {
//       customerId[count_id] = $(this).html();
//       count_id = count_id + 1; 
//     });
//     alert(customerId);
//     $.each(customerId,function(key,item){
//      alert(item);
      
//      $.ajax({
//         type: 'GET',
//         url: 'patients/export',
//         dataType: 'json',
//         data: { 
//           some_parameter: 'hello'
//         },
//         success:function(result){
//           alert(result);
//         }
//       });
//     });
//   });
// });
 </script>
<script type="text/javascript">
      $(document).ready(function(){
        $('.datepicker').datepicker();
      });
</script>
<h2>Search</h2>
<div class="table-responsive">
    
  <table class="records table">
       <thead>
      
        <tr>
          <td colspan='7'>
              <%= form_tag search_path, :method => 'get', :id => "patient_search" do %>
            <table>
              <tr>
                <td>
                  Select date Range
                </td>
                <td>
                  From date
                </td>
                <td>

                  <%= text_field_tag 'fromdate', params[:fromdate] , "data-provide"=>"datepicker", "placeholder" => "mm/dd/yyyy" %>
                </td>
                <td>
                  To date
                </td>
                <td>
                  <%= text_field_tag 'todate', params[:todate] , "data-provide"=>"datepicker", "placeholder" => "mm/dd/yyyy" %>
                </td>
              </tr>
           
        <tr>
          <td>
              Gender
              <%= select_tag "gender", options_for_select(['Male', 'Female', 'Other'], params[:gender]), :include_blank => 'ALL' %>
          </td>
          <td>
              Location
              <%= select_tag "location", options_for_select(["Prieto", "Sengstacke", "A.C.T.S. OF F.A.I.T.H.", "Ann & Robert H. Lurie Children’s Hospital","Cook County Health and Hospitals System (CCHHS)", "Erie Family Smart Health Centers", "Family Focus", "Health Leads – Chicago", "Heartland Health Outreach", "Komed Holman Smart Health Centers"], params[:location]), :include_blank => 'ALL' %>
          </td>
          <td>
              Topic
              <%= select_tag "topic", options_for_select(['Diabetes', 'Heart Disease', 'HIV', 'Asthma', 'Stroke', 'Excercise', 'Hypertension and Nutrition'], params[:topic]), :include_blank => 'ALL' %>
          </td>
          <td>
              Duration
              <%= select_tag "duration", options_for_select(['10 MIN', '20 MIN', '30 MIN', '40 MIN', '1 HR'], params[:duration]), :include_blank => 'ALL' %>
          </td>
          <td>
              Computer
              <%= select_tag "computer", options_for_select(['Yes', 'No'], params[:computer]), :include_blank => 'ALL' %>
          </td>
          <td>
              Type </br>
              <%= select_tag "type", options_for_select(['Group', 'Individual'], params[:type]), :include_blank => 'ALL' %>
          </td>
          <td>
              <%= submit_tag "Search", :name => 'search' %></p>
          </td>
        </tr>
        </table>
      <% end %>
          </td>
        </tr>
      <tr>
        <th>ID</th>
        <th>Initial Contact</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Language Spoken</th>
        <th>Own Computer</th>
        <th>Computer Skills</th>
        <th>Number Of Visits</th>
	      <th>Time Length</th>
	      <th>Interaction</th>
      </tr>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td id = "patient_id"><%= patient.id %></td>
          <td><%= formatted_date(patient.startdate) %></td>
          <td><%= patient.agerange %></td>
          <td><%= patient.gender %></td>
          <td><%= patient.languagespeaking %></td>
          <td><%= patient.computer %></td>
          <td><%= patient.computerskills %></td>
          <td><%= patient.noofvisits %></td>
	        <td><%= patient.timelength %></td>
	        <td><%= patient.noofinteraction %></td>
              </tr>
      <% end %>
       <tr>
            <td colspan="18" style="align:left;">
              <%= link_to "CSV", export_path(format: "csv"), class: "btn btn-primary btn-xs white get_patient_id" %> |
              <%= link_to "Excel", export_path(format: "xls"), class: "btn btn-primary btn-xs white get_patient_id" %>
            </td>
        </tr>
         <tr>
            <td colspan="10">
                <%= paginate @patients %>
            </td>
        </tr>
    </tbody>
  </table>
</div>	

app/views/patients/show.html.erb
<h2>Records</h2>
<%= render partial: "shared/notice" %>
<div class="table-responsive">
  <table class="records table">
    <tbody>
         <tr>
	<td width="20%">Location</td>
	<td><%= @patient.location %></td>
        </tr>
        <tr>
	<td width="20%">ID</td>
	<td><%= @patient.id %></td>
        </tr>
	<tr>
        <td>Initial Contact</td>
	<td><%= formatted_date(@patient.startdate) %></td>
	</tr>
	<tr>
        <td width="20%">Start Time</td>
	<td><%= formatted_time(@patient.starttime) %></td>
        </tr>
        <tr>
        <td>No Of Visits</td>
	<td><%= @patient.noofvisits %></td>
	</tr>
        <td>Group Id</td>
	<td><%= @patient.groupid %></td>
	</tr>
	<!--<tr>
        <td>Initial Contact</td>
	<td><%= @patient.initialcontact %></td>
	</tr>-->
	<tr>
        <td width="20%">Age Range</td>
	<td><%= @patient.agerange %></td>
        </tr>	
	<tr>
        <td>Gender</td>
	<td><%= @patient.gender %></td>
	</tr>

	<tr>
        <td>Preferred Language</td>
	<td><%= @patient.languagespeaking %></td>
	</tr>
	<tr>
        <td>Language Reading</td>
	<td><%= @patient.languagereading %></td>
	</tr>
	<tr>
	<td>Own Computer?</td>
	<td><%= @patient.computer %></td>
	</tr>
	<tr>
	<td>Computer Skills</td>
	<td><%= @patient.computerskills %></td>
	</tr>
	<tr>
	<td>Topic Discussed</td>
	<td><%= @patient.topicdiscussed %></td>
	</tr>
	<tr>
        <td>Time Length</td>
	<td><%= @patient.timelength %></td>
	</tr>
	<tr>
        <td>Notes</td>
	<td><%= @patient.notes %></td>
	</tr>
	<tr>
        <td>Participant (nos)</td>
	<td><%= @patient.noofparticipant %></td>
	</tr>
	<tr>
	<td>Inspection (nos)</td>
	<td><%= @patient.noofinteraction %></td>
	</tr>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'Records List', allrecords_path, class: "btn btn-primary white" %>	